test_that("NAMESPACE roxygen contract keeps expected exports and methods", {
  ns_file <- file.path(getNamespaceInfo("mfrmr", "path"), "NAMESPACE")
  expect_true(file.exists(ns_file))

  ns_lines <- readLines(ns_file, warn = FALSE)
  expect_true(any(grepl("^# Generated by roxygen2: do not edit by hand$", ns_lines)))

  exports <- sub("^export\\((.*)\\)$", "\\1", grep("^export\\(", ns_lines, value = TRUE))
  expected_exports <- c(
    "fit_mfrm",
    "describe_mfrm_data",
    "audit_mfrm_anchors",
    "make_anchor_table",
    "apa_table",
    "diagnose_mfrm",
    "interrater_agreement_table",
    "facets_chisq_table",
    "measurable_summary_table",
    "rating_scale_table",
    "specifications_report",
    "data_quality_report",
    "estimation_iteration_report",
    "subset_connectivity_report",
    "facet_statistics_report",
    "category_structure_report",
    "category_curves_report",
    "facets_output_file_bundle",
    "facets_parity_report",
    "unexpected_response_table",
    "unexpected_after_bias_table",
    "fair_average_table",
    "displacement_table",
    "analyze_residual_pca",
    "plot_residual_pca",
    "plot_unexpected",
    "plot_fair_average",
    "plot_displacement",
    "plot_bias_interaction",
    "plot_interrater_agreement",
    "plot_facets_chisq",
    "plot_qc_dashboard",
    "estimate_bias",
    "bias_count_table",
    "bias_interaction_report",
    "build_fixed_reports",
    "build_apa_outputs",
    "build_visual_summaries",
    "run_mfrm_facets",
    "mfrmRFacets",
    "mfrm_threshold_profiles",
    "list_mfrmr_data",
    "load_mfrmr_data",
    "export_mfrm",
    "plot_bubble"
  )
  expect_setequal(exports, expected_exports)

  s3 <- grep("^S3method\\(", ns_lines, value = TRUE)
  expected_s3 <- c(
    "S3method(print,mfrm_fit)",
    "S3method(print,mfrm_plot_bundle)",
    "S3method(print,mfrm_apa_text)",
    "S3method(print,apa_table)",
    "S3method(print,summary.apa_table)",
    "S3method(print,mfrm_data_description)",
    "S3method(print,mfrm_anchor_audit)",
    "S3method(print,mfrm_facets_run)",
    "S3method(print,summary.mfrm_data_description)",
    "S3method(print,summary.mfrm_anchor_audit)",
    "S3method(print,summary.mfrm_apa_outputs)",
    "S3method(print,summary.mfrm_facets_run)",
    "S3method(print,summary.mfrm_bundle)",
    "S3method(print,summary.mfrm_diagnostics)",
    "S3method(print,summary.mfrm_bias)",
    "S3method(print,summary.mfrm_fit)",
    "S3method(print,summary.mfrm_threshold_profiles)",
    "S3method(plot,apa_table)",
    "S3method(plot,mfrm_data_description)",
    "S3method(plot,mfrm_anchor_audit)",
    "S3method(plot,mfrm_facets_run)",
    "S3method(plot,mfrm_bundle)",
    "S3method(plot,mfrm_fit)",
    "S3method(summary,apa_table)",
    "S3method(summary,mfrm_data_description)",
    "S3method(summary,mfrm_anchor_audit)",
    "S3method(summary,mfrm_apa_outputs)",
    "S3method(summary,mfrm_facets_run)",
    "S3method(summary,mfrm_bundle)",
    "S3method(summary,mfrm_diagnostics)",
    "S3method(summary,mfrm_bias)",
    "S3method(summary,mfrm_fit)",
    "S3method(summary,mfrm_threshold_profiles)",
    "S3method(as.data.frame,mfrm_fit)"
  )
  expect_setequal(s3, expected_s3)
})
