load_conquest_execution_incident <- function() {
  skip_if_not_installed("digest")
  root <- normalizePath(testthat::test_path("..", ".."), mustWork = TRUE)
  validation <- file.path(root, "inst", "validation")
  required <- c(
    "conquest-prospective-tolerance-contract-0.2.3.R",
    "conquest-prospective-tolerance-freeze-0.2.3.R",
    "conquest-six-arm-candidate-binding-0.2.3.R",
    "conquest-six-arm-execution-incident-0.2.3.R"
  )
  paths <- file.path(validation, required)
  skip_if_not(all(file.exists(paths)),
              "Repository-only ConQuest incident review is excluded.")
  env <- new.env(parent = globalenv())
  for (path in paths) sys.source(path, envir = env)
  list(root = root, validation = validation, env = env)
}

test_that("candidate 002 semantic execution failure is retained", {
  ctx <- load_conquest_execution_incident()
  candidate_root <- file.path(
    ctx$root, ctx$env$mfrmr_cq_cb_candidate_root
  )

  if (dir.exists(candidate_root) && file.exists(file.path(
    candidate_root, "binary/q031a/cq_q031a_run.log"
  ))) {
    review <- ctx$env$mfrmr_cq_ei_review(candidate_root)
    expect_identical(
      review$status,
      "candidate_002_execution_failed_semantically_after_zero_process_exit"
    )
    expect_true(review$incident_confirmed)
    expect_identical(review$process_exit_status, 0L)
    expect_identical(
      review$failure_reason, "unsupported_c_style_prose_command_preamble"
    )
    expect_true(all(review$marker_present))
    expect_identical(nrow(review$present_outputs), 1L)
    expect_identical(review$present_outputs$ArmId, "binary_q031")
    expect_identical(review$present_outputs$OutputKind, "console_log")
    expect_identical(review$absent_output_count, 49L)
    expect_false(review$remaining_five_arms_launched)
    expect_false(review$candidate_binding_ready)
    expect_false(review$candidate_execution_authorized)
    expect_false(review$candidate_reuse_authorized)
    expect_true(review$candidate_003_required)
    expect_false(review$comparison_authorized)
    expect_false(review$scientific_equivalence_inferred)
    expect_false(review$confirmation_authorized)
  } else {
    expect_false(dir.exists(candidate_root) && file.exists(file.path(
      candidate_root, "binary/q031a/cq_q031a_run.log"
    )))
  }
})

test_that("generated Binary ConQuest command is executable-input only", {
  command <- mfrmr:::build_conquest_overlap_command_template(
    data_file = "fixture.csv",
    response_vars = c("I001", "I002"),
    covariate = "X",
    prefix = "fixture",
    quad_points = 31L
  )
  expect_true(startsWith(command[1L], "datafile "))
  expect_false(any(grepl("/*", command, fixed = TRUE)))
  expect_false(any(grepl("*/", command, fixed = TRUE)))
  expect_false(any(grepl("Generated by", command, fixed = TRUE)))
  expect_true(any(command == "model item;"))
  expect_true(any(grepl("nodes=31,", command, fixed = TRUE)))
})

test_that("the execution-incident record is source-bound", {
  ctx <- load_conquest_execution_incident()
  record_path <- file.path(
    ctx$validation, "conquest-six-arm-execution-incident-record-0.2.3.md"
  )
  expect_true(file.exists(record_path))
  record <- paste(readLines(record_path, warn = FALSE), collapse = "\n")
  artifacts <- c(
    file.path(
      ctx$validation, "conquest-six-arm-execution-incident-0.2.3.R"
    ),
    file.path(
      ctx$root, "tests", "testthat",
      "test-conquest-six-arm-execution-incident.R"
    )
  )
  hashes <- vapply(
    artifacts, digest::digest, character(1L),
    algo = "sha256", file = TRUE, serialize = FALSE
  )
  expect_true(all(vapply(
    hashes, grepl, logical(1L), x = record, fixed = TRUE
  )))
  identities <- c(
    ctx$env$mfrmr_cq_ei_candidate_id,
    ctx$env$mfrmr_cq_ei_command_sha256,
    ctx$env$mfrmr_cq_ei_console_sha256,
    ctx$env$mfrmr_cq_ei_failure_reason
  )
  expect_true(all(vapply(
    identities, grepl, logical(1L), x = record, fixed = TRUE
  )))
  expect_true(grepl("CandidateExecutionAuthorized.*FALSE", record))
  expect_true(grepl("ScientificEquivalenceInferred.*FALSE", record))
})
