#!/usr/bin/env Rscript
# Generated by mfrmr::build_mfrm_replay_script()
# Model: RSM | Method: MML
# Recorded mfrmr version: 0.2.4.9000

library(mfrmr)

# Version-mismatch warning. The replay script was generated against
# the recorded mfrmr version above. If the installed version differs
# the fit will still run, but estimates may diverge.
if (utils::packageVersion("mfrmr") != "0.2.4.9000") warning("replay.R was generated under mfrmr 0.2.4.9000; you are running ", as.character(utils::packageVersion("mfrmr")), ". ", "Estimates may differ.")

# Readiness provenance from the source fit. This is evidence to compare,
# not a status to copy into the replayed fit.
source_readiness <- structure(list(ReadinessContractVersion = "mfrmr-readiness-0.2.4-v1", 
    ReadinessScope = "fit", InputState = "pass", EstimabilityState = "identified", 
    CategoryState = "adequate", BoundaryState = "finite", NumericalState = "ready", 
    FitReadiness = "ready", InferenceReady = TRUE, ReasonCodes = "", 
    AuditProvenance = "fit_readiness_builder_v1;contract=mfrmr-readiness-0.2.4-v1;method=MML;model=RSM;scale=single_observed_scale"), class = "data.frame", row.names = c(NA, 
-1L))
source_readiness_components <- structure(list(Component = c("input", "estimability", "category", 
"boundary", "numerical"), State = c("pass", "identified", "adequate", 
"finite", "ready"), Complete = c(TRUE, TRUE, TRUE, TRUE, TRUE
), ReasonCodes = c("", "", "", "", ""), AuditState = c("pass;weights=unweighted", 
"identified", "adequate", "person=finite;jml=not_applicable", 
"severity=pass;status=converged;reason=tolerance_met"), AuditProvenance = c("prepare_mfrm_data_preparation_notes_v1;observation_weight_policy_v1", 
"constrained_adjacent_design_v1;method=MML;model=RSM", "declared_category_and_step_support_v1;model=RSM;scale=single_observed_scale", 
"person_sufficient_score_v1;method=MML;model=RSM", "common_terminal_gradient_gate_v1"
)), row.names = c(NA, -5L), class = "data.frame")
source_readiness_parameters <- structure(list(ReadinessContractVersion = character(0), ReadinessScope = character(0), 
    ParameterId = character(0), ParameterClass = character(0), 
    Facet = character(0), Level = character(0), OptimizerLogEstimate = numeric(0), 
    OptimizerEstimate = numeric(0), PrimaryLogEstimate = numeric(0), 
    PrimaryEstimate = numeric(0), ParameterStatus = character(0), 
    BoundaryDirection = character(0), SEEligible = logical(0), 
    CIEligible = logical(0), ComparisonEligibility = character(0), 
    PrimaryEstimateBasis = character(0), OptimizerEstimateUse = character(0), 
    ReasonCodes = character(0), AuditState = character(0), AuditProvenance = character(0)), class = "data.frame", row.names = integer(0))

data <- utils::read.csv("inst/validation/fair-joint-contract-0.2.4/RSM-80-3-data.csv", stringsAsFactors = FALSE)

# Stored constraints from the fitted analysis
anchors <- NULL
group_anchors <- NULL

# Population-model basis recorded in the fitted analysis
# population_active = FALSE
# posterior_basis = legacy_mml

# Fit the model
fit <- fit_mfrm(
  data = data,
  person = "Person",
  facets = c("Rater", "Criterion"),
  score = "Score",
  rating_min = 0L,
  rating_max = 2L,
  keep_original = FALSE,
  model = "RSM",
  method = "MML",
  gpcm_mml_identification = "free_population",
  min_obs_per_interaction = 10,
  interaction_policy = "warn",
  anchors = anchors,
  group_anchors = group_anchors,
  noncenter_facet = "Person",
  anchor_policy = "warn",
  min_common_anchors = 5L,
  min_obs_per_element = 30,
  min_obs_per_category = 10,
  quad_points = 61L,
  maxit = 200L,
  reltol = 1e-10,
  optimizer = "auto",
  mml_engine = "direct",
  facet_shrinkage = "none",
  shrink_person = FALSE,
  attach_diagnostics = FALSE
)

# Diagnostics
diagnostics <- diagnose_mfrm(fit, residual_pca = "none")

# Recompute readiness from the replayed fit; never inherit source status.
replay_readiness <- if (is.list(fit$readiness) && is.data.frame(fit$readiness$fit)) fit$readiness$fit else data.frame()
readiness_identity_fields <- c("ReadinessContractVersion", "ReadinessScope", "InputState", "EstimabilityState", "CategoryState", "BoundaryState", "NumericalState", "FitReadiness", "InferenceReady", "ReasonCodes", "AuditProvenance")
replay_readiness_matches_source <- nrow(replay_readiness) == 1L && all(readiness_identity_fields %in% names(replay_readiness)) && isTRUE(all.equal(source_readiness[, readiness_identity_fields, drop = FALSE], replay_readiness[, readiness_identity_fields, drop = FALSE], check.attributes = FALSE))
if (!replay_readiness_matches_source) warning("Replayed fit readiness differs from the source readiness provenance; inspect both records before using inferential outputs.", call. = FALSE)

bias_results <- NULL

population_prediction <- NULL

unit_prediction <- NULL

plausible_values <- NULL
