# Global variable declarations for dplyr NSE columns used in pipelines.
# These declarations keep R CMD check quiet without changing runtime behavior.
if (getRversion() >= "2.15.1") {
  utils::globalVariables(c(
    ".",
    ".context",
    ".FiniteGroupValue",
    ".Key",
    ".Level",
    ".NFinite",
    ".Row",
    ".ValidFacet",
    ".ValidGroup",
    ".ValidLevel",
    ".ValidValue",
    ".Weight",
    "AbsStd",
    "AbsZSTD",
    "Anchor",
    "AnchoredLevels",
    "Average",
    "Avg1",
    "Avg2",
    "AvgPersonMeasure",
    "Bias",
    "Bias Size",
    "Category",
    "ChiDf",
    "ChiP",
    "ChiSq",
    "ChosenGroupValue",
    "ConstrainedLevels",
    "Context1",
    "Context1 N",
    "Context2",
    "Context2 N",
    "Contrast",
    "Count",
    "Count1",
    "Count2",
    "d.f.",
    "DF",
    "DF_Infit",
    "DF_Outfit",
    "DiffPercent",
    "DistinctFiniteValues",
    "DistinctGroups",
    "DistinctValues",
    "Estimate",
    "EstimateVec",
    "Expctd",
    "Expctd Score",
    "Expected",
    "ExpectedAverage",
    "ExpectedCount",
    "ExpectedPercent",
    "Facet",
    "FacetA_Index",
    "FacetA_Level",
    "FacetA_Measure",
    "FacetB_Index",
    "FacetB_Level",
    "FacetB_Measure",
    "FairM",
    "FairZ",
    "FiniteValues",
    "FixedChiSq",
    "FixedDF",
    "FreeLevels",
    "Group",
    "GroupCount",
    "GroupedLevels",
    "GroupValue",
    "Infit",
    "InfitZSTD",
    "Info",
    "item_combination",
    "Label",
    "Level",
    "Levels",
    "Local",
    "Local Measure1",
    "Local Measure2",
    "MaxScore",
    "MeanAbsStdResidual",
    "MeanResidual",
    "MeanStdResidual",
    "Measure",
    "Measure1",
    "Measure2",
    "MinScore",
    "ModelSE",
    "N",
    "Obs-Exp",
    "Obs-Exp Average",
    "Obs-Exp Avg1",
    "Obs-Exp Avg2",
    "Observations",
    "Observd",
    "Observd Count",
    "Observd Score",
    "Observed",
    "ObservedAverage",
    "Ordered",
    "Outfit",
    "OutfitZSTD",
    "OverlapLevels",
    "p_Residual",
    "p_StdResidual",
    "Pair",
    "Percent",
    "PassMinObs",
    "Person",
    "PersonMeasure",
    "Prob.",
    "PTMEA",
    "RandomChiSq",
    "RandomDF",
    "RandomVar",
    "RealSE",
    "Residual",
    "RMSE",
    "Rows"
    ,
    "S.E.",
    "Score",
    "SE",
    "SE_Residual",
    "SE_StdResidual",
    "SE.x",
    "SE.y",
    "SE1",
    "SE2",
    "Separation",
    "SEVec",
    "Size",
    "Spacing",
    "Sq",
    "Status",
    "std_residual",
    "StdResidual",
    "StdSq",
    "Step",
    "StepFacet",
    "StepIndex",
    "Subset",
    "t_Residual",
    "t_StdResidual",
    "Target",
    "Target Measure",
    "Target N",
    "Target S.E.",
    "TotalCount",
    "TotalCountAll",
    "TotalScore",
    "Var",
    "Weight",
    "WeightedN",
    "WeightdCount",
    "WeightdScore"
  ))
}
