utils::globalVariables(c(
  ".",
  ".Level",
  ".Weight",
  ".context",
  "Abs",
  "AbsStd",
  "AbsZSTD",
  "Anchor",
  "AvgPersonMeasure",
  "Bias",
  "Bias Size",
  "Category",
  "ChiDf",
  "ChiP",
  "ChiSq",
  "Context1",
  "Context1 N",
  "Context2",
  "Context2 N",
  "Contrast",
  "Count",
  "Count1",
  "Count2",
  "DF",
  "DF_Infit",
  "DF_Outfit",
  "DiffPercent",
  "Estimate",
  "EstimateVec",
  "Expctd Score",
  "Expected",
  "ExpectedAverage",
  "ExpectedCount",
  "ExpectedPercent",
  "Facet",
  "FacetA_Index",
  "FacetA_Level",
  "FacetA_Measure",
  "FacetB_Index",
  "FacetB_Level",
  "FacetB_Measure",
  "FairM",
  "FairZ",
  "FixedChiSq",
  "FixedDF",
  "Group",
  "GroupValue",
  "Infit",
  "InfitMnSq",
  "InfitZSTD",
  "InfitZStd",
  "Info",
  "Label",
  "Level",
  "Levels",
  "Local Measure1",
  "Local Measure2",
  "MaxScore",
  "MeanAbsStdResidual",
  "MeanResidual",
  "MeanStdResidual",
  "Measure",
  "MinScore",
  "ModelSE",
  "N",
  "Obs-Exp Average",
  "Obs-Exp Avg1",
  "Obs-Exp Avg2",
  "Observations",
  "Observd Count",
  "Observd Score",
  "Observed",
  "ObservedAverage",
  "Ordered",
  "Outfit",
  "OutfitMnSq",
  "OutfitZSTD",
  "OutfitZStd",
  "Pair",
  "PTMEA",
  "Percent",
  "Person",
  "PersonMeasure",
  "Prob.",
  "PtMeaCorr",
  "RMSE",
  "RandomChiSq",
  "RandomDF",
  "RandomVar",
  "RealSE",
  "Residual",
  "S.E.",
  "SE",
  "SE.x",
  "SE.y",
  "SE1",
  "SE2",
  "SEVec",
  "SE_Residual",
  "SE_StdResidual",
  "Score",
  "Separation",
  "Spacing",
  "Sq",
  "Status",
  "StdResidual",
  "StdSq",
  "Step",
  "StepFacet",
  "StepIndex",
  "Subset",
  "Target",
  "Target Measure",
  "Target N",
  "Target S.E.",
  "TotalCount",
  "TotalCountAll",
  "TotalScore",
  "Var",
  "Weight",
  "WeightdCount",
  "WeightdScore",
  "d.f.",
  "item_combination",
  "p_Residual",
  "p_StdResidual",
  "std_residual",
  "t_Residual",
  "t_StdResidual"
))
