# Selected, purpose-based routes, not an inventory of every plot method.
.mfrmr_plot_guide <- function() {
  route <- function(question, input, call, name, component, conversion, notes) {
    data.frame(Question = question, InputClass = input, PlotCall = call,
      PlotName = name, DataComponent = component, GGPlot = conversion,
      GGPlotCall = if (conversion == "unavailable") NA_character_ else if (
        conversion == "native") "as_ggplot(x)" else if (conversion == "generic")
        sprintf('as_ggplot(p, component = "%s")', component) else "as_ggplot(p)",
      Notes = notes, stringsAsFactors = FALSE)
  }
  out <- rbind(
    route("Compare persons, facet levels and category steps", "mfrm_fit",
      'plot(x, type = "wright", draw = FALSE)', "wright_map", "locations", "dedicated",
      "Native Wright view. Respect source-model restrictions and uncertainty settings."),
    route("Show expected scores across ability", "mfrm_fit",
      'plot(x, type = "pathway", draw = FALSE)', "pathway_map", "expected", "dedicated",
      "A reference-profile prediction, not an average over the observed rating arrangement."),
    route("Review severity together with response fit", "mfrm_fit",
      'plot(x, type = "fit_pathway", draw = FALSE)', "fit_pathway", "table", "dedicated",
      "Severity and misfit are different; screening bands do not establish rater quality."),
    route("Inspect category functioning", "mfrm_fit",
      'plot(x, type = "ccc", draw = FALSE)', "category_characteristic_curves", "probabilities", "dedicated",
      "Predicted category probabilities; these curves alone do not show interval uncertainty."),
    route("Compare fixed-rater estimates and interval methods", "mfrm_facet_intervals",
      'plot(x, draw = FALSE)', "facet_interval_methods", "table", "dedicated",
      "Preserves saved intervals, fixed targets and unavailable intervals; no covariance is recomputed."),
    route("Show GPCM slope uncertainty", "mfrm_slope_intervals",
      'plot(x, draw = FALSE)', "gpcm_slope_intervals", "table", "native",
      "Already a ggplot. Use as_ggplot(x), not conversion of the extracted table; intervals remain approximate."),
    route("Show GPCM probability or information uncertainty", "mfrm_curve_intervals",
      'plot(x, draw = FALSE)', "gpcm_curve_intervals", "table", "native",
      "Already a ggplot. Saved inference target and unavailable intervals are retained; coverage is not guaranteed."),
    route("Compare observed raters in a shared-rater model", "mfrm_random_rater",
      'plot(x, draw = FALSE)', "random_rater_severity", "table", "dedicated",
      "Conditional severity estimates; normal intervals require an explicit approximation request."),
    route("Inspect testlet-model facet estimates", "mfrm_testlet",
      'plot(x, draw = FALSE)', "testlet_calibration", "table", "dedicated",
      "Select the facet for the intended comparison; normal intervals are an explicit approximation."),
    route("Review conditional Person scores from a shared-rater model", "mfrm_random_rater_scores",
      'plot(x, draw = FALSE)', "random_rater_scores", "table", "dedicated",
      "Conditional on saved calibration. Use style = 'precision' or 'distribution' for other views."),
    route("Review conditional Person scores from a testlet model", "mfrm_testlet_scores",
      'plot(x, draw = FALSE)', "testlet_scores", "table", "dedicated",
      "Conditional on saved calibration. Prior-only and unavailable scores are not ordinary observed estimates."),
    route("Review response fit under an extended model", "mfrm_response_diagnostics",
      'plot(x, draw = FALSE)', "response_diagnostics", "table", "dedicated",
      "Descriptive posterior predictive Infit/Outfit; ordinary plug-in cutoffs are not transferred."),
    route("Compare ordinary and extended model results", "mfrm_extended_comparison",
      'plot(x, draw = FALSE)', "extended_model_comparison", "table", "dedicated",
      "Comparison requires a common target and scale. A graphical difference is not a model-selection test."),
    route("Compare screening rules across known-truth conditions", "mfrm_screening_sensitivity",
      'plot(x, draw = FALSE)', "screening_sensitivity", "table", "dedicated",
      "Use style = 'curves' for trends. Simulation rates do not establish an observed rater's quality."),
    route("Show screening performance with uncertainty", "mfrm_screening_performance",
      'plot(x, draw = FALSE)', "screening_performance", "table", "unavailable",
      "Use the base plot and its saved table; Monte Carlo uncertainty differs from severity uncertainty."),
    route("Show pooled fixed-facet intervals after multiple imputation", "mfrm_pooled",
      'plot(x, draw = FALSE)', "pooled_facet_intervals", "table", "dedicated",
      "Saved pointwise MI t intervals; no repooling. Missingness and imputation-model assumptions remain."),
    route("Inspect separation of external-feature groups", "mfrm_clusters",
      'plot(x, type = "silhouette", draw = FALSE)', "cluster_silhouette", "table", "dedicated",
      "Descriptive clustering quality, not response-model fit or latent ability."),
    route("Describe an external feature within groups", "mfrm_clusters",
      'plot(x, type = "profile", feature = "Years", draw = FALSE)', "cluster_profile", "table", "dedicated",
      "Replace Years with one selected feature; categorical profiles also provide a matrix."),
    route("Inspect a hierarchy of external-feature groups", "mfrm_hierarchical_clusters",
      'plot(x, type = "dendrogram", draw = FALSE)', "cluster_dendrogram", "tree", "dedicated",
      "Gower dissimilarities and the recorded linkage; the tree does not establish latent dimensions."),
    route("Inspect group stability across feature imputations", "mfrm_imputed_clusters",
      'plot(x, draw = FALSE)', "cluster_co_membership", "matrix", "dedicated",
      "Pairwise co-membership fractions; preserve excluded IDs and unavailable cells."),
    route("Choose how many external-feature components to inspect", "mfrm_pca",
      'plot(x, type = "scree", draw = FALSE)', "feature_pca_scree", "table", "dedicated",
      "External-feature PCA, not a test of response-model dimensionality."),
    route("Locate entities on external-feature components", "mfrm_pca",
      'plot(x, type = "scores", draw = FALSE)', "feature_pca_scores", "table", "dedicated",
      "Requires two components; axes summarize the selected external features, not fitted ability."),
    route("Identify features contributing to a component", "mfrm_pca",
      'plot(x, type = "loadings", draw = FALSE)', "feature_pca_loadings", "table", "dedicated",
      "Loadings depend on the recorded centering and scaling choices."),
    route("Plan facet counts with an observed-score D-study", "mfrm_d_study",
      'plot(x, type = "coefficients", draw = FALSE)', "d_study", "series", "unavailable",
      "Base plots also offer error_variance, heatmap, contour and surface3d; other varying conditions need explicit panels."),
    route("Plan reliability for a multivariate score or composite", "mfrm_multivariate_d_study",
      'plot(x, type = "coefficients", draw = FALSE)', "multivariate_d_study", "series", "dedicated",
      "Choose score or composite when necessary. Observed-score projections omit variance-component uncertainty."),
    route("Plan absolute or relative error in score units", "mfrm_multivariate_d_study",
      'plot(x, type = "sem", draw = FALSE)', "multivariate_d_study", "series", "dedicated",
      "SEM is in the selected score's units; retain score identity and composite weights."),
    route("Compare D-study scenarios with difference intervals", "mfrm_multivariate_d_comparison",
      'plot(x, type = "coefficients", draw = FALSE)', "multivariate_d_comparison", "table", "unavailable",
      "Use the base comparison plot; it is distinct from the point-projection curves."),
    route("Inspect observed coverage across rating subsets", "mfrm_bundle",
      'plot(x, type = "design_matrix", draw = FALSE)', "subset_connectivity", "matrix", "generic",
      "Use a subset_connectivity_report() result. Matrix conversion omits the observation-share panel. Coverage alone does not establish connectedness or a missingness mechanism."),
    route("Customize the underlying precision values", "mfrm_information",
      'plot_information(x, type = "tif", draw = FALSE)', "information_tif", "plot", "generic",
      "This component becomes points from its first two numeric columns. Generic conversion does not reproduce the base curve or its annotations.")
  )
  creators <- c(mfrm_fit = "fit_mfrm", mfrm_facet_intervals = "mfrm_facet_intervals",
    mfrm_slope_intervals = "confint.mfrm_fit", mfrm_curve_intervals = "mfrm_curve_intervals",
    mfrm_random_rater = "fit_mfrm_random_rater", mfrm_testlet = "fit_mfrm_testlet",
    mfrm_random_rater_scores = "score_mfrm_random_rater", mfrm_testlet_scores = "predict.mfrm_testlet",
    mfrm_response_diagnostics = "mfrm_response_diagnostics", mfrm_extended_comparison = "compare_mfrm",
    mfrm_screening_sensitivity = "mfrm_screening_sensitivity",
    mfrm_screening_performance = "mfrm_screening_performance", mfrm_pooled = "pool_mfrm_imputed",
    mfrm_clusters = "mfrm_cluster", mfrm_hierarchical_clusters = "mfrm_cluster_hierarchical",
    mfrm_imputed_clusters = "mfrm_cluster_imputed", mfrm_pca = "mfrm_pca",
    mfrm_bundle = "subset_connectivity_report", mfrm_d_study = "mfrm_d_study", mfrm_multivariate_d_study = "mfrm_multivariate_d_study",
    mfrm_multivariate_d_comparison = "mfrm_multivariate_d_compare", mfrm_information = "compute_information")
  out$ResultFunction <- unname(creators[out$InputClass])
  out$NextStep <- ifelse(out$GGPlot == "unavailable",
    "Draw PlotCall with draw = TRUE; extract DataComponent with plot_data(p, component = ...).",
    "Use GGPlotCall; inspect DataComponent with plot_data(p, component = ...) before interpreting the figure.")
  out
}
